#! bash

umask 077
function sudo {
    ( umask 022; command sudo "$@" )
}

function __path_prepend {
    local dir new_path IFS=':'
    for dir in ${!2}; do
        [ "$dir" == "$1" ] && continue
        new_path="$new_path:$dir"
    done
    export $2="$1$new_path"
}

__path_prepend /usr/share/man MANPATH
__path_prepend /opt/share/man MANPATH
__path_prepend /usr/local/share/man MANPATH
__path_prepend /usr/local/opt/coreutils/libexec/gnuman MANPATH
__path_prepend /usr/local/opt/gnu-sed/libexec/gnuman MANPATH
__path_prepend /usr/local/opt/gnu-tar/libexec/gnuman MANPATH
__path_prepend /usr/local/opt/libressl/share/man MANPATH

__path_prepend /sbin PATH
__path_prepend /bin PATH
__path_prepend /usr/sbin PATH
__path_prepend /usr/bin PATH
__path_prepend /opt/sbin PATH
__path_prepend /opt/bin PATH
__path_prepend /usr/local/sbin PATH
__path_prepend /usr/local/bin PATH
__path_prepend /usr/local/opt/coreutils/libexec/gnubin PATH
__path_prepend /usr/local/opt/gnu-sed/libexec/gnubin PATH
__path_prepend /usr/local/opt/gnu-tar/libexec/gnubin PATH
__path_prepend /usr/local/opt/libressl/bin PATH
__path_prepend "$HOME/.bin" PATH
__path_prepend "$HOME/bin" PATH

__path_prepend "$HOME/gocode" GOPATH
__path_prepend "$HOME/gocode/bin" PATH
